// <auto-generated />
using System;
using Komisija.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Komisija.Migrations
{
    [DbContext(typeof(KomisijaContext))]
    [Migration("20230218021308_imigration")]
    partial class imigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Komisija.Models.KomisijaModel", b =>
                {
                    b.Property<Guid>("komisijaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("nazivKomisije")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("oznakaKomisije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("komisijaId");

                    b.ToTable("Komisije");
                });

            modelBuilder.Entity("Komisija.Models.LicnostKomisije", b =>
                {
                    b.Property<Guid>("licnostKomisijeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KomisijaModelkomisijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("datumRodjenjaLicnostiKomisije")
                        .HasColumnType("datetime2");

                    b.Property<string>("funkcijaLicnostiKomisije")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("imeLicnostiKomisije")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<Guid>("komisijaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("kontaktLicnostiKomisije")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("oznakaKomisije")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prezimeLicnostiKomisije")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("licnostKomisijeId");

                    b.HasIndex("KomisijaModelkomisijaId");

                    b.ToTable("LicnostiKomisije");
                });

            modelBuilder.Entity("Komisija.Models.LicnostKomisije", b =>
                {
                    b.HasOne("Komisija.Models.KomisijaModel", null)
                        .WithMany("clanoviKomisije")
                        .HasForeignKey("KomisijaModelkomisijaId");
                });
#pragma warning restore 612, 618
        }
    }
}
