// <auto-generated />
using System;
using JavnoNadmetanje.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace JavnoNadmetanje.Migrations
{
    [DbContext(typeof(JavnoNadmetanjeContext))]
    [Migration("20230217164531_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("JavnoNadmetanje.Models.JavnoNadmetanjeModel", b =>
                {
                    b.Property<Guid>("JavnoNadmetanjeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdresaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojUcesnika")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumNadmetanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("IzlicitiranaCena")
                        .HasColumnType("int");

                    b.Property<bool>("Izuzeto")
                        .HasColumnType("bit");

                    b.Property<int>("KatastarskaOpstina")
                        .HasColumnType("int");

                    b.Property<int>("Krug")
                        .HasColumnType("int");

                    b.Property<Guid>("KupacID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LicitacijaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParcelaID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PeriodZakupa")
                        .HasColumnType("int");

                    b.Property<int>("PocetnaCenaPoHektaru")
                        .HasColumnType("int");

                    b.Property<int>("PrijavljeniKupci")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("Tip")
                        .HasColumnType("int");

                    b.Property<int>("VisinaDopuneDepozita")
                        .HasColumnType("int");

                    b.Property<DateTime>("VremeKraja")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremePocetka")
                        .HasColumnType("datetime2");

                    b.HasKey("JavnoNadmetanjeID");

                    b.ToTable("JavnaNadmetanja");
                });
#pragma warning restore 612, 618
        }
    }
}
